### ISSUE TITLE
cuwire as alternative to leo

### ISSUE THREAD

**Issue by apla** [AdamMagaluk/leo#24]
Hi!

I have tried to use `leo` and [ino](http://inotool.org) as cli tool to work with arduino sketches and failed. Seems `leo` and `ino` development is frozen.

So, I decided to write my own, [cuwire](http://apla.github.io/cuwire/). Please take a look. cuwire doesn't support leo libraries as npm modules (I think it is bad practice — arduino libraries have nothing common with npm) and you must crete `.ino` file by hand.

Otherwise, it work beautiful.

**Comment by AdamMagaluk** [comment]
Hi Apla,

Sorry things weren't working for you. Leo is still in a very experimental form but things in the README should work properly now. If you have any specific issues I'd be happy to respond with possible fixes.

Cuwire looks great, was thinking of doing a Atom plugin for leo at some point myself. Definitely will give a try.

My biggest complaint with the Arduino build system and any other embedded programing IDEs is dealing with reuse of code for libraries. Generally you have to download a zip from somewhere extract and add it to your IDE. I am hoping to improve upon this for the Arduino/Arduino Compatible boards by using `npm` to distribute libraries. While `npm` and arduino libs don't directly have much in common i do believe it can be used to distribute any form of code more than just node packages. As `npm` is already needed to install leo I think it makes sense.

Best of luck with cuwire :)
